apiVersion: v1
kind: Secret
metadata:
  name: minioaccess
  namespace: kubeflow
data:
  AZURE_STORAGE_ACCESS_KEY: V0h3Vm5mZmM1MHdiSlA2L0J0R3VmMmtZZjV3WEozTTREQ1JmcTFqSlJ0YmhZQjhUVWdRd05XN0pPOFFWZXpFTlhCSHRGUE0vR2lVeCtBU3RIS01tbXc9PQo=
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWN2YXQwMHRlc3Q7QWNjb3VudEtleT1XSHdWbmZmYzUwd2JKUDYvQnRHdWYya1lmNXdYSjNNNERDUmZxMWpKUnRiaFlCOFRVZ1F3Tlc3Sk84UVZlekVOWEJIdEZQTS9HaVV4K0FTdEhLTW1tdz09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQK
  MLFLOW_TRACKING_USERNAME: ZGVlcGVjaG8K
  MLFLOW_TRACKING_PASSWORD: ZGVlcGVjaG9tbGZsb3cK
  BACKEND_URI: cG9zdGdyZXNxbDovL2RlZXBlY2hvQGRlZXBlY2hvMG1sZmxvdzB0ZXN0OkNsaW5pY2Fsc3R1ZHkyMDIyQGRlZXBlY2hvMG1sZmxvdzB0ZXN0LnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbS9tbGZsb3dfZGIK


